# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.CharField(blank=True, max_length=2000, null=True)),
                ('audio_url', models.IntegerField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['extract'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['theme'],
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('excerpt', models.ManyToManyField(blank=True, to='interviews.Excerpt')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.Location')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'women',
            },
        ),
        migrations.AddField(
            model_name='excerpt',
            name='images',
            field=models.ManyToManyField(blank=True, to='interviews.Images'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='themes',
            field=models.ManyToManyField(blank=True, to='interviews.Themes'),
        ),
    ]
