# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerpt',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
