# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20171120_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='excerpt',
        ),
    ]
