# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_remove_women_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='excerpt',
            name='women',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.Women'),
        ),
    ]
