# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_excerpt_women'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerpt',
            name='images',
        ),
        migrations.RemoveField(
            model_name='excerpt',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='excerpt',
            name='women',
        ),
        migrations.DeleteModel(
            name='Excerpt',
        ),
    ]
