# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20171120_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.CharField(blank=True, max_length=2000, null=True)),
                ('audio_url', models.IntegerField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='interviews.Images')),
                ('themes', models.ManyToManyField(blank=True, to='interviews.Themes')),
                ('women', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.Women')),
            ],
            options={
                'ordering': ['extract'],
            },
        ),
    ]
