# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='audio_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
