# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_auto_20171120_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['title'], 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city'], 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['location', 'name'], 'verbose_name_plural': 'women'},
        ),
        migrations.AddField(
            model_name='excerpt',
            name='clip_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
